modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="end_crown"
version="1.0.0"
displayName="End Crown"
logoFile = "mod_logo.png"
authors = "符百珀"
description='''
终焉冠冕 —— 超越生死的桂冠
'''